## Read_csv

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('people_data.csv')

In [3]:
df.head()

,First Name,Last Name,Sex,Email,Date of birth,Job Title
0,Shelby,Terrell,Male,elijah57@example.net,1945-10-26,Games developer
1,Phillip,Summers,Female,bethany14@example.com,1910-03-24,Phytotherapist
2,Kristine,Travis,Male,bthompson@example.com,1992-07-02,Homeopath
3,Yesenia,Martinez,Male,kaitlinkaiser@example.com,2017-08-03,Market researcher
4,Lori,Todd,Male,buchananmanuel@example.net,1938-12-01,Veterinary surgeon

In [8]:
df = pd.read_csv('people_data.csv',usecols=['First Name','Last Name'])
df.head()

  First Name Last Name
0     Shelby   Terrell
1    Phillip   Summers
2   Kristine    Travis
3    Yesenia  Martinez
4       Lori      Todd

In [10]:
df= pd.read_csv('people_data.csv',index_col='First Name')
print(df)

           Last Name     Sex                       Email Date of birth  \
First Name
Shelby       Terrell    Male        elijah57@example.net    1945-10-26
Phillip      Summers  Female       bethany14@example.com    1910-03-24
Kristine      Travis    Male       bthompson@example.com    1992-07-02
Yesenia     Martinez    Male   kaitlinkaiser@example.com    2017-08-03
Lori            Todd    Male  buchananmanuel@example.net    1938-12-01

                     Job Title
First Name
Shelby         Games developer
Phillip         Phytotherapist
Kristine             Homeopath
Yesenia      Market researcher
Lori        Veterinary surgeon

In [12]:
df = pd.read_csv('people_data.csv',na_values=['N/A','unknown'])
print(df)

  First Name Last Name     Sex                       Email Date of birth  \
0     Shelby   Terrell    Male        elijah57@example.net    1945-10-26
1    Phillip   Summers  Female       bethany14@example.com    1910-03-24
2   Kristine    Travis    Male       bthompson@example.com    1992-07-02
3    Yesenia  Martinez    Male   kaitlinkaiser@example.com    2017-08-03
4       Lori      Todd    Male  buchananmanuel@example.net    1938-12-01

            Job Title
0     Games developer
1      Phytotherapist
2           Homeopath
3   Market researcher
4  Veterinary surgeon

In [13]:
import pandas as pd

data = """totalbill_tip, sex:smoker, day_time, size
16.99, 1.01:Female|No, Sun, Dinner, 2
10.34, 1.66, Male, No|Sun:Dinner, 3
21.01:3.5_Male, No:Sun, Dinner, 3
23.68, 3.31, Male|No, Sun_Dinner, 2
24.59:3.61, Female_No, Sun, Dinner, 4
25.29, 4.71|Male, No:Sun, Dinner, 4"""

with open('sample.csv','w') as file:
    file.write(data)
print(data)

totalbill_tip, sex:smoker, day_time, size
16.99, 1.01:Female|No, Sun, Dinner, 2
10.34, 1.66, Male, No|Sun:Dinner, 3
21.01:3.5_Male, No:Sun, Dinner, 3
23.68, 3.31, Male|No, Sun_Dinner, 2
24.59:3.61, Female_No, Sun, Dinner, 4
25.29, 4.71|Male, No:Sun, Dinner, 4

In [18]:
df = pd.read_csv('sample.csv',sep='[,_|:]')
print(df)

   totalbill   tip      sex smoker   day     time   size
0      16.99  1.01   Female     No   Sun   Dinner      2
1      10.34  1.66     Male     No   Sun   Dinner      3
2      21.01  3.50     Male     No   Sun   Dinner      3
3      23.68  3.31     Male     No   Sun   Dinner      2
4      24.59  3.61   Female     No   Sun   Dinner      4
5      25.29  4.71     Male     No   Sun   Dinner      4

C:\Users\rajen\AppData\Local\Temp\ipykernel_18740\494720934.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df = pd.read_csv('sample.csv',sep='[,_|:]')

In [22]:
df = pd.read_csv('sample.csv',sep='[_,:|]',nrows=3,engine='python')
print(df)

   totalbill   tip     sex smoker   day     time   size
0      16.99  1.01  Female     No   Sun   Dinner      2
1      10.34  1.66    Male     No   Sun   Dinner      3
2      21.01  3.50    Male     No   Sun   Dinner      3

In [25]:
df = pd.read_csv('sample.csv',sep='[_,:|]',engine= 'python',skiprows=[4,5])
print(df)
df = pd.read_csv('sample.csv',sep='[_,:|]',engine= 'python')
print(df)

   totalbill   tip     sex smoker   day     time   size
0      16.99  1.01  Female     No   Sun   Dinner      2
1      10.34  1.66    Male     No   Sun   Dinner      3
2      21.01  3.50    Male     No   Sun   Dinner      3
3      25.29  4.71    Male     No   Sun   Dinner      4
   totalbill   tip      sex smoker   day     time   size
0      16.99  1.01   Female     No   Sun   Dinner      2
1      10.34  1.66     Male     No   Sun   Dinner      3
2      21.01  3.50     Male     No   Sun   Dinner      3
3      23.68  3.31     Male     No   Sun   Dinner      2
4      24.59  3.61   Female     No   Sun   Dinner      4
5      25.29  4.71     Male     No   Sun   Dinner      4

In [28]:
df = pd.read_csv('people_data.csv',sep=',',parse_dates=['Date of birth'])
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   First Name     5 non-null      str
 1   Last Name      5 non-null      str
 2   Sex            5 non-null      str
 3   Email          5 non-null      str
 4   Date of birth  5 non-null      datetime64[us]
 5   Job Title      5 non-null      str
dtypes: datetime64[us](1), str(5)
memory usage: 372.0 bytes

In [29]:
url = "https://media.geeksforgeeks.org/wp-content/uploads/20241121154629307916/people_data.csv"
df = pd.read_csv(url)
df.head()

,First Name,Last Name,Sex,Email,Date of birth,Job Title
0,Shelby,Terrell,Male,elijah57@example.net,1945-10-26,Games developer
1,Phillip,Summers,Female,bethany14@example.com,1910-03-24,Phytotherapist
2,Kristine,Travis,Male,bthompson@example.com,1992-07-02,Homeopath
3,Yesenia,Martinez,Male,kaitlinkaiser@example.com,2017-08-03,Market researcher
4,Lori,Todd,Male,buchananmanuel@example.net,1938-12-01,Veterinary surgeon

## Read_Excel

In [31]:
import pandas as pd
df = pd.read_excel('students.xlsx')
df.head()

   Roll No.  English  Maths  Science
0         1       19     13       17
1         2       14     20       18
2         3       15     18       19
3         4       13     14       14
4         5       17     16       20

In [42]:
import pandas as pd
sheet1 = pd.read_excel('students.xlsx',sheet_name=0,index_col=0)
print(sheet1)

sheet2 = pd.read_excel('students.xlsx',sheet_name=1,index_col=0)
print(sheet2)

sheet = pd.concat([sheet1,sheet2])
print(sheet)

          English  Maths  Science
Roll No.
1              19     13       17
2              14     20       18
3              15     18       19
4              13     14       14
5              17     16       20
6              19     13       17
7              14     20       18
8              15     18       19
9              13     14       14
10             17     16       20
          English  Maths  Science
Roll No.
1              14     18       20
2              11     19       18
3              12     18       16
4              15     18       19
5              13     14       14
6              14     18       20
7              11     19       18
8              12     18       16
9              15     18       19
10             13     14       14
          English  Maths  Science
Roll No.
1              19     13       17
2              14     20       18
3              15     18       19
4              13     14       14
5              17     16       20
6              19     13       17
7              14     20       18
8              15     18       19
9              13     14       14
10             17     16       20
1              14     18       20
2              11     19       18
3              12     18       16
4              15     18       19
5              13     14       14
6              14     18       20
7              11     19       18
8              12     18       16
9              15     18       19
10             13     14       14

In [43]:
sheet.head()

          English  Maths  Science
Roll No.
1              19     13       17
2              14     20       18
3              15     18       19
4              13     14       14
5              17     16       20

In [44]:
sheet.tail()

          English  Maths  Science
Roll No.
6              14     18       20
7              11     19       18
8              12     18       16
9              15     18       19
10             13     14       14

In [45]:
sheet.shape

(20, 3)

In [49]:
sheet.sort_values(by=['English'],ascending= False)

          English  Maths  Science
Roll No.
1              19     13       17
6              19     13       17
5              17     16       20
10             17     16       20
9              15     18       19
4              15     18       19
3              15     18       19
8              15     18       19
6              14     18       20
2              14     20       18
7              14     20       18
1              14     18       20
4              13     14       14
9              13     14       14
10             13     14       14
5              13     14       14
8              12     18       16
3              12     18       16
2              11     19       18
7              11     19       18

In [50]:
sheet.describe()

        English      Maths    Science
count  20.00000  20.000000  20.000000
mean   14.30000  16.800000  17.500000
std     2.29645   2.330575   2.164304
min    11.00000  13.000000  14.000000
25%    13.00000  14.000000  16.000000
50%    14.00000  18.000000  18.000000
75%    15.00000  18.000000  19.000000
max    19.00000  20.000000  20.000000

In [51]:
sheet['English'].mean()

np.float64(14.3)

In [52]:
sheet['Total Marks'] = sheet["English"] + sheet["Maths"] + sheet["Science"]
sheet['Total Marks'].head()

Roll No.
1    49
2    52
3    52
4    41
5    53
Name: Total Marks, dtype: int64

In [54]:
sheet.to_excel('new_sheet.xlsx')

## Working With JSON Data in Python

In [62]:
import json
a = {
    'name':'raju',
    'age':23,
    'email':'raju@gmail.com'
}
b = json.dumps(a)
print(b)

{"name": "raju", "age": 23, "email": "raju@gmail.com"}

In [63]:
import json
json.dumps(['welcome','to','baitadi'])

'["welcome", "to", "baitadi"]'

In [64]:
json.dumps(('welcome','to','baitadi'))

'["welcome", "to", "baitadi"]'

In [65]:
json.dumps('hi')

'"hi"'

In [66]:
json.dumps(123)

'123'

In [67]:
json.dumps(True)

'true'

### Serializing JSON

In [69]:
import json
marks = {
    'student1':{
        'math':50,
        'english':65,
        'nepali':78
    },
    'student2':{
        'math':50,
        'english':65,
        'nepali':78
    }
}

with open(file='serializable.json',mode='w') as file:
    json.dump(marks,file)

### Deserializing JSON

In [75]:
import json
with open(file='serializable.json',mode='r') as read_it:
    data = json.load(read_it)
    print(type(data))

<class 'dict'>

In [78]:
json_var ="""
{
    "Country": {
        "name": "INDIA",
        "Languages_spoken": [
            {
                "names": ["Hindi", "English", "Bengali", "Telugu"]
            }
        ]
    }
}
"""

json.loads(json_var)

{'Country': {'name': 'INDIA',
  'Languages_spoken': [{'names': ['Hindi', 'English', 'Bengali', 'Telugu']}]}}

### Export Pandas Dataframe to a CSV file

When working on a Data Science project one of the key tasks is data management which includes data collection, cleaning and storage. Once our data is cleaned and processed it's essential to save it in a structured format for further analysis or sharing.

CSV (Comma-Separated Values) file is a widely used format for storing tabular data. Pandas provides to_csv() function to export a DataFrame into a CSV file.

In [82]:
import pandas as pd

scores = {'Name': ['a', 'b', 'c', 'd'],
          'Score': [90, 80, 95, 20]}

df = pd.DataFrame(scores)
print(df)

  Name  Score
0    a     90
1    b     80
2    c     95
3    d     20

In [84]:
df.to_csv("your_name.csv")

#### Customizing the CSV Export 
1. Remove Index Column

In [85]:
df.to_csv('your_name.csv',index=False)

2. Export only selected columns

In [87]:
df.to_csv('your_name.csv',index=False,columns=['Name'])

3. Exclude Header Row

In [88]:
df.to_csv('your_name.csv',index=False,header=False)

4. Handling Missing Values

In [90]:
df.to_csv('your_name.csv',index=False,na_rep ='nothing')

5. Change Column Separator

In [91]:
df.to_csv('your_name.csv',index=False,sep='\t')

## Exporting Pandas DataFrame to JSON File

In [92]:
import pandas as pd

df = pd.DataFrame([['a', 'b', 'c'], ['d', 'e', 'f'], ['g', 'h', 'i']],
                  index=['row 1', 'row 2', 'row 3'],
                  columns=['col 1', 'col 2', 'col 3'])

In [98]:
df.to_json('file.json',orient='split',compression='infer',index=True)

In [101]:
df = pd.read_json('file.json',orient='split',compression='infer')
print(df)

      col 1 col 2 col 3
row 1     a     b     c
row 2     d     e     f
row 3     g     h     i

In [102]:
import pandas as pd

df = pd.DataFrame(data=[
    ['15135', 'Alex', '25/4/2014'],
    ['23515', 'Bob', '26/8/2018'],
    ['31313', 'Martha', '18/1/2019'],
    ['55665', 'Alen', '5/5/2020'],
    ['63513', 'Maria', '9/12/2020']],
    columns=['ID', 'NAME', 'DATE OF JOINING'])

In [103]:
df.to_json('file1.json',orient='split')

In [105]:
df = pd.read_json('file1.json',orient='split')
print(df)

      ID    NAME DATE OF JOINING
0  15135    Alex       25/4/2014
1  23515     Bob       26/8/2018
2  31313  Martha       18/1/2019
3  55665    Alen        5/5/2020
4  63513   Maria       9/12/2020

## Slicing Pandas Dataframe

In [106]:
import pandas as pd

player_list = [['M.S.Dhoni', 36, 75, 5428000],
               ['A.B.D Villers', 38, 74, 3428000],
               ['V.Kohli', 31, 70, 8428000],
               ['S.Smith', 34, 80, 4428000],
               ['C.Gayle', 40, 100, 4528000],
               ['J.Root', 33, 72, 7028000],
               ['K.Peterson', 42, 85, 2528000]]

df = pd.DataFrame(player_list, columns=['Name', 'Age', 'Weight', 'Salary'])
print(df)

            Name  Age  Weight   Salary
0      M.S.Dhoni   36      75  5428000
1  A.B.D Villers   38      74  3428000
2        V.Kohli   31      70  8428000
3        S.Smith   34      80  4428000
4        C.Gayle   40     100  4528000
5         J.Root   33      72  7028000
6     K.Peterson   42      85  2528000

#### Slicing Using iloc[] (Integer-Based Indexing)

In [108]:
df.iloc[0:4]

            Name  Age  Weight   Salary
0      M.S.Dhoni   36      75  5428000
1  A.B.D Villers   38      74  3428000
2        V.Kohli   31      70  8428000
3        S.Smith   34      80  4428000

In [109]:
df.iloc[:,0:2]

            Name  Age
0      M.S.Dhoni   36
1  A.B.D Villers   38
2        V.Kohli   31
3        S.Smith   34
4        C.Gayle   40
5         J.Root   33
6     K.Peterson   42

In [110]:
df.iloc[2,0]

'V.Kohli'

In [113]:
df[df['Age']>35]

            Name  Age  Weight   Salary
0      M.S.Dhoni   36      75  5428000
1  A.B.D Villers   38      74  3428000
4        C.Gayle   40     100  4528000
6     K.Peterson   42      85  2528000

#### Slicing Using loc[]

In [ ]:
df.set_index('Name',inplace=True)

In [ ]:
df.loc['M.S.Dhoni':'C.Gayle']

               Age  Weight   Salary
Name
M.S.Dhoni       36      75  5428000
A.B.D Villers   38      74  3428000
V.Kohli         31      70  8428000
S.Smith         34      80  4428000
C.Gayle         40     100  4528000

In [118]:
df.loc['M.S.Dhoni':'C.Gayle','Age':'Salary']

               Age  Weight   Salary
Name
M.S.Dhoni       36      75  5428000
A.B.D Villers   38      74  3428000
V.Kohli         31      70  8428000
S.Smith         34      80  4428000
C.Gayle         40     100  4528000

In [119]:
df.loc['V.Kohli','Salary']

np.int64(8428000)